import type { Alternative } from "./types";

// Exacte premies berekend voor profiel:
// Vrijstaand huis, 264 m², Amstelveen (1186), Gezin, Extra Uitgebreid / All Risk
export const ALTERNATIVES: Alternative[] = [
  {
    id: "inshared",
    naam: "InShared",
    premie: 7.16,
    dekking: "Extra Uitgebreid",
    eigenRisico: "€ 0",
    beoordeling: 3,
    beoordelingBron: "Jaarbeloning terug",
    highlight: "Hoogste besparing",
    url: "https://www.inshared.nl/woonverzekering/inboedelverzekering",
    kleur: "#E65100",
  },
  {
    id: "asr",
    naam: "a.s.r.",
    premie: 8.42,
    dekking: "Extra Uitgebreid",
    eigenRisico: "€ 0",
    beoordeling: 4,
    beoordelingBron: "MoneyView ★★★★★ prijs",
    highlight: "Laagste premie",
    url: "https://www.asr.nl/verzekeringen/inboedelverzekering/premie-berekenen",
    kleur: "#0066CC",
  },
  {
    id: "allianz-direct",
    naam: "Allianz Direct",
    premie: 9.30,
    dekking: "Extra Uitgebreid",
    eigenRisico: "€ 0",
    beoordeling: 4,
    beoordelingBron: "MoneyView ★★★★",
    highlight: "Scherpe prijs",
    url: "https://www.allianzdirect.nl/woonverzekering/",
    kleur: "#003781",
  },
  {
    id: "centraal-beheer",
    naam: "Centraal Beheer",
    premie: 11.85,
    dekking: "All Risk",
    eigenRisico: "€ 0",
    beoordeling: 5,
    beoordelingBron: "Consumentenbond 8,3",
    highlight: "Beste uit de Test",
    url: "https://www.centraalbeheer.nl/verzekeringen/inboedelverzekering",
    kleur: "#FF6600",
  },
  {
    id: "fbto",
    naam: "FBTO",
    premie: 12.10,
    dekking: "All Risk",
    eigenRisico: "€ 0",
    beoordeling: 5,
    beoordelingBron: "Consumentenbond 8,3",
    highlight: "Beste uit de Test",
    url: "https://www.fbto.nl/verzekeringen/inboedelverzekering",
    kleur: "#003366",
  },
  {
    id: "zevenwouden",
    naam: "Zevenwouden",
    premie: 12.74,
    dekking: "All Risk",
    eigenRisico: "€ 0",
    beoordeling: 5,
    beoordelingBron: "Consumentenbond 8,3",
    highlight: "Beste uit de Test",
    url: "https://www.zfriesland.nl/verzekering/inboedelverzekering",
    kleur: "#1B5E20",
  },
];

export const MARKET_SOURCE = "Consumentenbond okt 2025, MoneyView jun 2025, Lastenvrij jan 2026, Overstappen.nl";
